### ISSUE TITLE
Handling surrogate pairs

### ISSUE THREAD

**Issue by nishimotz** [zeithaste/cursorCharCode#1]
The Unicode code point tool for VSCode 0.0.4 is very useful, however, the character such as the first symbol of this is reported as U+D83D.
I am afraid surrogate pairs are not handled correctly.

```
💛	1f49b	[ハート]	ハートノ エモジ
```

**Comment by zeithaste** [comment]
Thank you for raising the issue, hopefully it works as expected now.

**Comment by nishimotz** [comment]
Perfect. Thank you.
