### ISSUE TITLE
View not updated after deleting text

### ISSUE THREAD

**Issue by ygoe** [zeithaste/cursorCharCode#10]
1. Type an arbitrary letter like `a` (U+0061)
2. Move the cursor in front of that character
3. The status bar shows U+0061
4. Press the <kbd>Delete</kbd> key (forward delete, not backspace)

The status bar now still shows the deleted character when it should instead show what now comes after the cursor.

I guess the delete event isn't handled by the extension yet, but I have no clue actually how this works.

**Comment by zeithaste** [comment]
Yeah, this looks like a bug. Thanks, I'll take a look at it.

**Comment by zeithaste** [comment]
`Delete` should update the status bar item now
