### ISSUE TITLE
Add an icon to the extension

### ISSUE THREAD

**Issue by ygoe** [zeithaste/cursorCharCode#11]
I'm adding this extension to my website as recommendation, and I'm including the extension icons there. It looks a little lame with no icon for it. 😉

I could try to draw one if you like. Probably something that shows the "U+xxxx" text and a cursor or so.

**Comment by zeithaste** [comment]
When I created the extension, I made it for myself, so I didn't feel any need for an icon.
I'm not very good at design, so I'd love to see your ideas, if you already have some.

**Comment by ygoe** [comment]
Just revisiting this… Can you please explain to me what this `$(telescope)` is? It seems to render as an icon but I can't find it anywhere online (inside or outside this repository).

https://github.com/zeithaste/cursorCharCode/blob/master/src/extension.ts#L172

**Comment by zeithaste** [comment]
It's one of the built-in icons, you can find it [in this reference list](https://code.visualstudio.com/api/references/icons-in-labels).

**Comment by ygoe** [comment]
Ah, I see. They use the "codicon" font. But I couldn't fit it in the logo anyway, so here's my suggestion:

![cursorCharCode-logo](https://github.com/zeithaste/cursorCharCode/assets/868315/d3aa3776-2209-4f2b-a955-7c9f071be313)

(Select the text around the image to see its exact size because it has a partially white background.)

I can also provide it in .svg or .afdesign formats. The font is Segoe UI that comes with Windows and is used by Microsoft everywhere.

**Comment by zeithaste** [comment]
Looks nice!
Let me see what I can do with that

**Comment by zeithaste** [comment]
feel free to re-open if you want any changes ;-)

**Comment by ygoe** [comment]
Cool! You could add the SVG version of it to the repo in case somebody wants to edit the icon later. (Right-click on the image and select "Save target as" or "Save image as", at least in Firefox.)

![cursorCharCode-logo](https://github.com/zeithaste/cursorCharCode/assets/868315/3f923ffd-0008-45fe-99d2-d408fca6d71a)

**Comment by zeithaste** [comment]
Thank you, I saved it in [here](https://github.com/zeithaste/cursorCharCode/blob/master/resource/icon.svg) just in case.
