### ISSUE TITLE
The external url unicode-table should be changed - or make it customizable

### ISSUE THREAD

**Issue by leonbloy** [zeithaste/cursorCharCode#14]
unicode-table.com redirects to https://symbl.cc/ which has some issues (ads, custom font with missing glyphs...)

I think it would be bettter to direct to https://codepoints.net/U+xxxx , or make it customizable

**Comment by zeithaste** [comment]
I agree that symbl's interface is rather ugly, and ad-ridden.
As for codepoints.net, I consider it too cluttered for my taste.

I'll change the URL to https://www.compart.com/en/unicode/U+xxxx - this one is the most neutral-looking I've found.

**Comment by zeithaste** [comment]
The link update has been published on the marketplace.
