### ISSUE TITLE
add link to unicode-table.com

### ISSUE THREAD

**Issue by WebFreak001** [zeithaste/cursorCharCode#2]
When clicking the text in the status bar it should open a browser with unicode information (for example https://unicode-table.com/en/1F363/)

**Comment by zeithaste** [comment]
There you go :)

**Comment by WebFreak001** [comment]
thanks! really useful extension for quickly embedding char codes inside source code. Maybe commands like `Replace character to \xFF form`, `Replace character to \uFFFF form` and `Replace character to \uFFFFFFFF form` would be useful too.
