### ISSUE TITLE
How to use this extention in vscode?

### ISSUE THREAD

**Issue by sighWang** [zeithaste/cursorCharCode#4]

**Comment by zeithaste** [comment]
Once you install it, an icon with a telescope appears in the status bar whenever you're inside an editable document. It shows the code point of the symbol after the cursor. It shows a page describing the Unicode character when you click on it.

There appear a couple of new commands as well, allowing to replace the current character with it's unicode form. You can find them it you open the command pallette (Ctrl+Shift+P) and choose one of the commands starting with CursorCharCode.
