### ISSUE TITLE
[Feature Request] Use tooltip/hover text to display the decimal equivalent

### ISSUE THREAD

**Issue by Antagony1060** [zeithaste/cursorCharCode#6]
This would be useful for HTML coders, where it is more usual to enter the decimal value – eg: `&#65;` for A – rather than the hex value.

**Comment by zeithaste** [comment]
I'm afraid using a hover or tooltip will interfere with other VS code functionality, so I've added a couple of commands (hexToClipboard, decToClipboard) which you can bind to a shortcut and get the decimal or hex code in your clipboard.

**Comment by Antagony1060** [comment]
That's even better, thanks!
